apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "msm.fullname" . }}-leader-election-role
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: msm-nc
    app.kubernetes.io/part-of: msm-nc
  {{- include "msm.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "msm.fullname" . }}-leader-election-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: msm-nc
    app.kubernetes.io/part-of: msm-nc
  {{- include "msm.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "msm.fullname" . }}-leader-election-role'
subjects:
  - kind: ServiceAccount
    name: '{{ include "msm.fullname" . }}-controller-manager'
    namespace: '{{ .Release.Namespace }}'