apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "msm.fullname" . }}-manager-role
  labels:
  {{- include "msm.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - mediastreams.media-streaming-mesh.io
    resources:
      - streamdata
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - mediastreams.media-streaming-mesh.io
    resources:
      - streamdata/finalizers
    verbs:
      - update
  - apiGroups:
      - mediastreams.media-streaming-mesh.io
    resources:
      - streamdata/status
    verbs:
      - get
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "msm.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: msm-nc
    app.kubernetes.io/part-of: msm-nc
  {{- include "msm.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "msm.fullname" . }}-manager-role'
subjects:
  - kind: ServiceAccount
    name: '{{ include "msm.fullname" . }}-controller-manager'
    namespace: '{{ .Release.Namespace }}'