# webhook
apiVersion: v1
kind: Service
metadata:
  name: msm-admission-webhook-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: msm-admission-webhook
    {{- include "MSM.labels" . | nindent 4 }}
spec:
  ports:
    - name: ssl
      port: 443
      targetPort: 443
  selector:
    app: msm-admission-webhook
