# change this to desired Kubernetes Distribution e.g. "K8S" or "K3S"
kubernetesDistro: "K3S"

cpUrl: "http://msm-cp:9000"

cniImage:
  name: ghcr.io/media-streaming-mesh/msm-cni
  tag: latest

proxyImage:
  name: ghcr.io/media-streaming-mesh/msm-dp
  tag: latest

stubImage:
  name: ghcr.io/media-streaming-mesh/msm-rtsp-stub
  tag: latest

webhookImage:
  name: ghcr.io/media-streaming-mesh/msm-admission-webhook
  tag: latest
