# webhook-prep
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: msm-admission-webhook-role
  labels:
    {{- include "MSM.labels" . | nindent 4 }}
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
  - apiGroups: ["admissionregistration.k8s.io"]
    resources:
      - "mutatingwebhookconfigurations"
    verbs: ["*"]
---
#cni-prep
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: msm-cni
  labels:
    app: msm-cni
    {{- include "MSM.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources:
      - pods
      - nodes
    verbs:
      - get
      - list
      - watch
---
# cp-prep
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: msm-cp
  labels:
    app: msm-cp
    {{- include "MSM.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources:
      - namespaces
      - services
      - nodes
      - endpoints
    verbs:
      - list
      - get
  - apiGroups: [""]
    resources:
      - nodes
    verbs:
      - watch
  - apiGroups: ["apiextensions.k8s.io"]
    resources:
      - customresourcedefinitions
    verbs:
      - '*'
  - apiGroups: ["mediastreamingmesh.io"]
    resources: ["*"]
    verbs: ["*"]
